/* 好友约战浏览器端：只发送操作，不决定规则和随机结果。 */
(()=>{'use strict';
const b=window.RTCGBattle,$=id=>document.getElementById(id),make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const configured=String(window.RTCG_PVP_SERVER||'').trim().replace(/\/+$/,'');
const serverBase=configured||(/^https?:$/.test(location.protocol)?location.origin:'');
function endpoint(path){if(!serverBase)throw new Error('联机服务尚未配置，当前可以继续进行单人对战。');const url=new URL(serverBase);if(!['https:','http:'].includes(url.protocol))throw new Error('联机服务地址无效。');return serverBase+path;}
let auth=null,source=null,connected=false,room=null,seat=0,seq=0,lastState=null,queue=[],playing=false,choiceId=null,epoch=0,latestPacket=null,selectedDecks=[],selectedDeckKey=localStorage.getItem('rtcg-pvp-deck')||'';
const section=make('section');section.id='pvpPage';section.hidden=true;document.querySelector('main').append(section);
const style=make('style');style.textContent=`#openPlayerBattle{opacity:1;background:linear-gradient(140deg,#eef0ff,#e6f5ff)}#pvpPage{max-width:850px;margin:20px auto;color:#263e50}.pvp-shell{padding:28px;border:1px solid #c6dbe4;border-radius:24px;background:linear-gradient(145deg,#f5fbff,#e6f0f4);box-shadow:0 12px 40px #234c6620}.pvp-shell h1{margin:0 0 18px}.pvp-form{display:grid;gap:12px}.pvp-form label{font-weight:700}.pvp-form input,.pvp-form select{width:100%;padding:12px;border-radius:10px;border:1px solid #aac7d8;background:#fff;box-sizing:border-box}.pvp-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:18px}.pvp-actions button{padding:11px 19px;border-radius:12px}.pvp-code{font:800 38px/1.2 Arial,sans-serif;letter-spacing:8px;color:#2879ae;margin:18px 0}.pvp-seats{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:16px 0}.pvp-seat{padding:18px;background:#fff;border:2px solid #b9d7e8;border-radius:15px}.pvp-seat.foe{border-color:#e3bac4}.pvp-seat strong{display:block;font-size:20px}.pvp-seat small{display:block;margin-top:10px;color:#657c8f}.pvp-status{margin:12px 0;color:#56778b}.pvp-error{color:#b13c52}.pvp-badge{font-size:12px;margin-left:12px;display:flex;align-items:center;gap:8px;flex-wrap:wrap}.pvp-badge button{padding:4px 8px;font-size:11px}.pvp-toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);z-index:200;background:#263f55;color:#fff;padding:12px 20px;border-radius:12px;box-shadow:0 5px 15px #0003;max-width:90vw}@media(max-width:600px){.pvp-shell{padding:18px}.pvp-seats{gap:8px}.pvp-seat{padding:12px}.pvp-code{font-size:30px}}`;document.head.append(style);
const previousShow=showPage;showPage=function(page){section.hidden=page!=='pvp';previousShow(page);if(page!=='battle')document.querySelector('.battle-result-layer')?.setAttribute('hidden','');if(page==='pvp')paint();};
const menuButton=$('openPlayerBattle');menuButton.querySelector('span:not(.menu-icon)').textContent='创建房间或输入房间码，与好友联机对战';menuButton.onclick=()=>{showPage('pvp');if(!auth)resume();};
function toast(message){document.querySelector('.pvp-toast')?.remove();const n=make('div',message,'pvp-toast');n.setAttribute('role','alert');document.body.append(n);setTimeout(()=>n.remove(),4000);}
async function post(action,data={}){const response=await fetch(endpoint('/api/'+action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,token:auth?.token})});const result=await response.json();if(!response.ok)throw new Error(result.error||'连接失败。');return result;}
function mapOwner(owner){return owner===seat?0:1;}
function remap(state){const g=structuredClone(state),original=g.players;g.players=[original[seat],original[1-seat]];g.current=mapOwner(g.current);g.first=mapOwner(g.first);const winning=original.findIndex(p=>g.winner===p.label+'获胜');g.players[0].label='玩家';g.players[1].label='对手';g.players[0].displayName=room.players[seat]?.name||'玩家';g.players[1].displayName=room.players[1-seat]?.name||'对手';if(winning>=0)g.winner=winning===seat?'玩家获胜':'对手获胜';if(g.contributions)g.contributions=[g.contributions[seat],g.contributions[1-seat]];return g;}
function remapEvent(event,state){const e={...event};if(e.owner!==undefined)e.owner=mapOwner(e.owner);if(e.type==='turn'||e.type==='end'){e.owner=mapOwner(state.current);e.title=(e.owner===0?'我的回合':'对手的回合')+(e.type==='end'?'结束':'');}return e;}
function remember(){sessionStorage.setItem('rtcg-pvp-session',JSON.stringify(auth));}
function configure(){b.networkConfigure({role:'client',send:sendCommand,leave:leave,finishRoom:()=>showPage('pvp')});}
function connect(){source?.close();connected=false;source=new EventSource(endpoint('/api/events?token='+encodeURIComponent(auth.token)));source.onopen=()=>{connected=true;paintBadge();};source.onerror=()=>{connected=false;paintBadge();};source.onmessage=e=>{let packet;try{packet=JSON.parse(e.data)}catch{return;}if(packet.seq<seq)return;seq=packet.seq;room=packet.room;seat=packet.seat;if(packet.state)latestPacket=packet;
 if(packet.type==='snapshot'){epoch++;queue=[];playing=false;choiceId=null;$('battleChoice')?.close();configure();}
 queue.push({...packet,epoch});void drain();};}
async function resume(){try{const saved=JSON.parse(sessionStorage.getItem('rtcg-pvp-session')||'null');if(!saved)return;auth=saved;const result=await post('resume');Object.assign(auth,result);room=result.room;seat=result.seat;configure();connect();paint();}catch{auth=null;sessionStorage.removeItem('rtcg-pvp-session');paint();}}
async function enter(action){try{const result=await post(action,{name:$('pvpName').value,code:$('pvpCodeInput')?.value});auth=result;room=result.room;seat=result.seat;localStorage.setItem('rtcg-pvp-name',$('pvpName').value);seq=0;remember();configure();connect();paint();}catch(e){toast(e.message);}}
function drainState(packet){if(!packet.state)return;if(b.choice&&(packet.type==='presence'||packet.choice?.id===choiceId)){lastState=remap(packet.state);paintBadge();return;}lastState=remap(packet.state);b.networkLoad(lastState,{locked:!!packet.locked,setup:room.phase==='setup'&&!room.players[seat].setupReady});paintBadge();}
async function drain(){if(playing)return;playing=true;const currentEpoch=epoch;try{while(queue.length&&currentEpoch===epoch){const packet=queue.shift();if(packet.epoch!==epoch)continue;room=packet.room;seat=packet.seat;
 if(room.phase==='lobby'){lastState=null;choiceId=null;showPage('pvp');continue;}
 if(!packet.state){paint();continue;}
 if(room.phase==='finished'&&!section.hidden){lastState=remap(packet.state);paint();continue;}
 if(packet.type==='event'){const event=remapEvent(packet.event,packet.state);if(event.type==='turn')event.owner=mapOwner(packet.state.current);await b.networkEvent(event,remap(packet.state));if(currentEpoch!==epoch)break;lastState=remap(packet.state);paintBadge();}
 else {drainState(packet);if(packet.choice&&packet.choice.id!==choiceId){choiceId=packet.choice.id;const id=choiceId;void b.networkPrompt(packet.choice).then(value=>{if(id===choiceId&&auth)sendCommand('choice',{choiceId:id,value});});}}
 if(room.phase==='finished')decorateResult();
 }}catch(e){if(currentEpoch!==epoch)return;console.error('联机显示失败',e);const latest=latestPacket;if(latest?.state){queue=[];room=latest.room;seat=latest.seat;configure();choiceId=null;$('battleChoice')?.close();try{drainState(latest);if(latest.choice){choiceId=latest.choice.id;const id=choiceId;void b.networkPrompt(latest.choice).then(value=>{if(id===choiceId&&auth)sendCommand('choice',{choiceId:id,value});});}if(room.phase==='finished')decorateResult();toast('已恢复当前场面。');}catch(renderError){console.error('联机场面恢复失败',renderError);toast('场面显示失败，请重新打开对局页面。');}}}finally{if(currentEpoch===epoch){playing=false;if(queue.length)void drain();}}}
async function sendCommand(action,data){try{if(!connected)throw new Error('连接已断开，正在重连。');const aliases={setupDone:'setupDone',setupUndo:'setupUndo'};await post(aliases[action]||action,{...data,seq});if(action==='choice')choiceId=null;}catch(e){toast(e.message);if(connected&&auth)connect();}}
function deckKey(d){return d.id||JSON.stringify([d.name,d.cards,d.energies]);}
async function rematch(){showPage('pvp');try{await post('rematch');}catch(e){toast(e.message);}}
async function ready(){try{const deck=selectedDecks.find(d=>deckKey(d)===$('pvpDeck')?.value);if(!deck||!b.validDeck(deck))throw new Error('请先选择有效的自建卡组。');await post('ready',{deck});}catch(e){toast(e.message);}}
async function leave(){if(auth&&['setup','play'].includes(room?.phase)&&!confirm('离开会结束本局，确定离开吗？'))return;try{if(auth)await post('leave');}catch{}source?.close();auth=null;room=null;lastState=null;latestPacket=null;epoch++;queue=[];playing=false;choiceId=null;connected=false;sessionStorage.removeItem('rtcg-pvp-session');$('battleChoice')?.close();$('battleInspect')?.close();b.networkConfigure(null);showPage('menu');}
function button(text,fn,disabled=false){const n=make('button',text);n.disabled=disabled;n.onclick=fn;return n;}
function deckTransfer(shell){const actions=make('div',undefined,'pvp-actions');actions.append(button('导出我的卡组',()=>{const blob=new Blob([JSON.stringify({decks:savedDecks},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=make('a');link.href=url;link.download='roco-decks.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}),button('导入卡组',()=>{const input=make('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{if(!input.files?.length)return;const raw=JSON.parse(await input.files[0].text());const count=b.importDecks(Array.isArray(raw)?raw:raw.decks);toast('已导入'+count+'组卡组。');paint();}catch(e){toast(e.message);}finally{input.remove();}};input.hidden=true;document.body.append(input);input.addEventListener('cancel',()=>input.remove(),{once:true});input.click();}));shell.append(actions);}
function paint(){if(section.hidden)return;section.replaceChildren();const shell=make('div',undefined,'pvp-shell');shell.append(make('h1','好友约战'),make('small','版本 '+b.cardsVersion,'pvp-status'));section.append(shell);
 if(!auth){const form=make('div',undefined,'pvp-form'),name=make('input');name.id='pvpName';name.maxLength=20;name.value=localStorage.getItem('rtcg-pvp-name')||'小洛克';form.append(make('label','你的昵称'),name);const input=make('input');input.id='pvpCodeInput';input.inputMode='numeric';input.maxLength=6;input.placeholder='输入6位房间码';input.value=new URLSearchParams(location.search).get('room')||'';form.append(make('label','房间码'),input);shell.append(form);const actions=make('div',undefined,'pvp-actions');actions.append(button('创建房间',()=>enter('create')),button('加入房间',()=>enter('join')),button('返回菜单',()=>showPage('menu')));shell.append(actions);deckTransfer(shell);if(!serverBase)shell.append(make('p','联机服务尚未部署；部署完成后，直接打开本文件即可约战。','pvp-status'));return;}
 shell.append(make('div',auth.code,'pvp-code'));const players=make('div',undefined,'pvp-seats');for(const i of [seat,1-seat]){const p=room.players[i],card=make('div',undefined,'pvp-seat'+(i!==seat?' foe':''));card.append(make('strong',p?p.name:'等待好友加入'),make('small',p?(p.online?'已连接':'正在连接／离线')+' · '+(p.ready?'已准备':'未准备'): '分享房间码或邀请链接'));players.append(card);}shell.append(players);
 const actions=make('div',undefined,'pvp-actions');actions.append(button('复制房间码',async()=>{try{await navigator.clipboard.writeText(auth.code);toast('房间码已复制，好友打开自己的游戏并输入即可。');}catch{toast('房间码：'+auth.code);}}));
 if(room.phase==='lobby'){selectedDecks=[...savedDecks];if(!selectedDecks.some(d=>deckKey(d)===selectedDeckKey&&b.validDeck(d)))selectedDeckKey=deckKey(selectedDecks.find(d=>b.validDeck(d))||{id:''});const select=make('select');select.id='pvpDeck';selectedDecks.forEach((d,i)=>{const o=make('option',d.name);o.value=deckKey(d);o.disabled=!b.validDeck(d);select.append(o);});select.value=selectedDeckKey;select.disabled=room.players[seat].ready||!selectedDecks.length;select.onchange=()=>{selectedDeckKey=select.value;localStorage.setItem('rtcg-pvp-deck',selectedDeckKey);};shell.append(make('label','本局卡组'),select);if(!selectedDecks.length)shell.append(make('p','请先在组建卡组中保存卡组，或导入自己的卡组。','pvp-status'));actions.append(button(room.players[seat].ready?'已准备':'准备对战',ready,room.players[seat].ready||!selectedDecks.some(d=>b.validDeck(d))));shell.append(make('p','双方准备后进入初始布阵。','pvp-status'));}
 else if(room.phase==='finished'){actions.append(button(room.players[seat].again?'等待对方再战':'再战一局',rematch,room.players[seat].again));}
 else actions.append(button('返回对局',()=>{if(lastState)b.networkLoad(lastState,{locked:playing,setup:room.phase==='setup'&&!room.players[seat].setupReady});}));
 actions.append(button('离开房间',leave));shell.append(actions);if(room.phase==='lobby')deckTransfer(shell);}
function paintBadge(){if(!auth||$('battlePage').hidden)return;const header=$('battlePage').querySelector('.header');if(!header)return;let badge=header.querySelector('.pvp-badge');if(!badge){badge=make('div',undefined,'pvp-badge');header.append(badge);}badge.replaceChildren(make('span',`房间 ${auth.code} · ${room.players[seat]?.name||'我方'} vs ${room.players[1-seat]?.name||'对手'} · ${connected?'已连接':'正在重连'}`));if(['setup','play'].includes(room.phase))badge.append(button('认输',()=>{if(confirm('确定认输吗？'))post('surrender').catch(e=>toast(e.message));}));}
function decorateResult(){const overlay=$('battleResult');const target=overlay||document.querySelector('.battle-result-layer');if(!target)return;if(!section.hidden){target.hidden=true;return;}const panel=target.querySelector('.result-panel');if(panel&&!panel.querySelector('.pvp-rematch')){const again=button(room.players[seat].again?'等待对方再战':'再来一局',rematch,room.players[seat].again);again.className='pvp-rematch';panel.append(again);}const back=target.querySelector('.result-return');if(back){back.textContent='返回约战房间';back.onclick=()=>{target.hidden=true;showPage('pvp');};}}
const observer=new MutationObserver(()=>{paintBadge();if(room?.phase==='finished')decorateResult();});observer.observe($('battlePage'),{childList:true});
window.RTCGPvp={get room(){return room},get identity(){return auth},get connected(){return connected},get sequence(){return seq},get settled(){return !playing&&!queue.length},leave,post,sendCommand};
if(new URLSearchParams(location.search).has('room'))showPage('pvp');
})();
