'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),createEngine=require('./engine.cjs');
const ROOT=path.resolve(__dirname,'..'),PORT=Number(process.env.PORT||3000),GRACE=Number(process.env.RECONNECT_SECONDS||60)*1000;
const rooms=new Map(),sessions=new Map(),rate=new Map(),maxRooms=Number(process.env.MAX_ROOMS||100),assetRoot=path.join(ROOT,'所有卡图');
const clone=x=>JSON.parse(JSON.stringify(x));const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})};const token=()=>crypto.randomBytes(24).toString('base64url');
function publicRoom(r){return {code:r.code,phase:r.phase,round:r.round,players:r.players.map(p=>p?{name:p.name,ready:!!p.ready,setupReady:!!p.setupReady,online:!!p.stream,again:!!p.again,background:p.deck?.background||'default',sleeve:p.deck?.sleeve||'default'}:null)};}
function seatOf(r,t){const seat=r.players.findIndex(p=>p?.token===t);if(seat<0)fail('身份已失效，请重新加入房间。',401);return seat;}
function view(r,seat){if(!r.engine?.state)return null;const g=clone(r.engine.state);g.players=g.players.map((p,i)=>{p.deckCount=p.deck.length;p.deck=Array(p.deck.length).fill(null);if(i!==seat)p.hand=Array(p.hand.length).fill(null);if(g.phase==='setup'&&!g.revealed&&i!==seat){const concealed=m=>m?{uid:m.uid,slot:m.slot??null,concealed:true}:null;p.active=concealed(p.active);p.bench=p.bench.map(concealed);}return p;});return g;}
function send(p,data){if(p?.stream&&!p.stream.destroyed)p.stream.write('data: '+JSON.stringify(data)+'\n\n');}
function choiceFor(r,seat){return r.pending?.owner===seat?{id:r.pending.id,title:r.pending.title,options:r.pending.options,optional:r.pending.optional,...(r.pending.title==='选择加入手牌的精灵（向对方展示）'?{searchCards:r.engine.state.players[seat].deck.slice().sort()}:{}),...(r.pending.allocation||{})}:null;}
function packet(r,seat,type='state',extra={}){return {type,seq:r.seq,room:publicRoom(r),seat,state:view(r,seat),locked:r.running||r.players[seat].setupReady&&r.phase==='setup',choice:choiceFor(r,seat),...extra};}
function publish(r,type='state',extra={}){r.seq++;r.updated=Date.now();for(let seat=0;seat<2;seat++)if(r.players[seat])send(r.players[seat],packet(r,seat,type,extra));}
async function event(r,e){r.seq++;r.updated=Date.now();for(let seat=0;seat<2;seat++){const p=r.players[seat];if(!p)continue;const safe={...e};if((e.type==='networkDraw'&&!e.reveal||e.type==='networkSetupPlace')&&e.owner!==seat)safe.cardId=null;send(p,packet(r,seat,'event',{event:safe}));}}
function choose(r,owner,title,options,optional){return new Promise((resolve,reject)=>{r.pending={id:token(),owner,title,options:clone(options).map(({score,...o})=>o),optional,resolve,reject};publish(r);});}
function engineFor(r){return createEngine({event:e=>event(r,e),choose:(...args)=>choose(r,...args),allocate:(owner,prompt)=>new Promise((resolve,reject)=>{r.pending={id:token(),owner,title:prompt.title,options:clone(prompt.options).map(({score,...o})=>o),optional:prompt.optional,allocation:clone({...prompt,options:undefined}),resolve,reject};publish(r);})});}
function validateDeck(r,d){if(!d||!Array.isArray(d.cards)||d.cards.length>20||!d.cards.every(x=>typeof x.id==='string'&&/^A(?:0|1[ab])-\d{3}$/.test(x.id)&&Number.isInteger(x.count)&&x.count>=1&&x.count<=2)||!Array.isArray(d.energies)||d.energies.length>11||!d.energies.every(x=>typeof x==='string'&&x.length<=12)||!r.engine.validDeck(d))fail('卡组不符合规则：20张卡、同名最多2张，并包含基础精灵和能量类型。');return clone(d);}
function finish(r,winner,reason){if(!r.engine?.state||r.phase==='finished')return;r.phase='finished';r.running=false;r.engine.state.winner=winner;r.engine.state.log.push(reason);const pending=r.pending;r.pending=null;if(pending)pending.reject(new Error(reason));publish(r);}
async function run(r,fn){if(r.running)fail('上一个操作正在结算。',409);r.running=true;publish(r);try{await fn();if(r.engine.state.winner)r.phase='finished';}catch(e){if(r.phase!=='finished'){console.error('对局结算错误',r.code,e.message);finish(r,'平局','对局结算异常，本局结束。');}}finally{r.running=false;if(!r.pending)publish(r);}}
function checked(r,t){const seat=seatOf(r,t);return {r,seat,p:r.players[seat]};}
function code(){let c;do{c=crypto.randomInt(100000,1000000).toString();}while(rooms.has(c));return c;}
function create(name){if(rooms.size>=maxRooms)fail('房间已满，请稍后重试。',503);const r={code:code(),players:[null,null],phase:'lobby',seq:0,round:1,running:false,pending:null,updated:Date.now()};r.engine=engineFor(r);rooms.set(r.code,r);return join(r,0,name);}
function join(r,seat,name){const p={name:String(name||'洛克').trim().slice(0,20)||'洛克',token:token(),ready:false,setupReady:false,stream:null};r.players[seat]=p;sessions.set(p.token,r.code);publish(r);return {token:p.token,code:r.code,seat,room:publicRoom(r)};}
async function body(req){let bytes=0,raw='';for await(const chunk of req){bytes+=chunk.length;if(bytes>64*1024)fail('请求太大。',413);raw+=chunk;}try{return JSON.parse(raw||'{}')}catch{fail('请求格式错误。')}}
async function api(req,res,url){const ip=req.socket.remoteAddress,now=Date.now(),bucket=rate.get(ip)||{start:now,count:0};if(now-bucket.start>60000){bucket.start=now;bucket.count=0;}if(++bucket.count>600)fail('操作过于频繁，请稍后重试。',429);rate.set(ip,bucket);
 if(req.method==='GET'&&url.pathname==='/api/events'){const t=url.searchParams.get('token'),r=rooms.get(sessions.get(t));if(!r)fail('房间已关闭。',404);const seat=seatOf(r,t),p=r.players[seat];if(p.stream)p.stream.end();clearTimeout(p.disconnectTimer);res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});p.stream=res;res.write(': connected\n\n');send(p,packet(r,seat,'snapshot'));publish(r,'presence');const heartbeat=setInterval(()=>res.write(': keepalive\n\n'),15000);req.on('close',()=>{clearInterval(heartbeat);if(p.stream!==res)return;p.stream=null;publish(r,'presence');if(['setup','play'].includes(r.phase))p.disconnectTimer=setTimeout(()=>{if(!p.stream&&['setup','play'].includes(r.phase)){const other=r.players[1-seat];finish(r,other?.stream?'玩家'+(2-seat)+'获胜':'平局','断线超过重连等待时间。');}},GRACE);});return;}
 if(req.method!=='POST')fail('不支持的请求。',405);const d=await body(req);let result;
 if(url.pathname==='/api/create')result=create(d.name);
 else if(url.pathname==='/api/join'){const r=rooms.get(String(d.code));if(!r)fail('房间不存在或已过期。',404);if(r.phase!=='lobby'||r.players[1])fail('房间已经满员或正在对战。',409);result=join(r,1,d.name);}
 else {const r=rooms.get(sessions.get(d.token));if(!r)fail('房间已关闭。',404);const {seat,p}=checked(r,d.token);
 switch(url.pathname){
 case '/api/resume':result={token:p.token,code:r.code,seat,room:publicRoom(r)};break;
 case '/api/ready':if(r.phase!=='lobby')fail('本局已经开始。',409);p.deck=validateDeck(r,d.deck);p.ready=d.ready!==false;publish(r);if(r.players.every(x=>x?.ready)){r.phase='setup';r.players.forEach(x=>x.setupReady=false);r.engine.networkCreate(r.players.map(x=>x.deck));publish(r);for(let i=0;i<2;i++)r.engine.state.players[i].displayName=r.players[i].name;void event(r,{type:'intro',title:'对战入场',duration:2300});void event(r,{type:'coin',title:'判定先后手',toss:true,landing:r.engine.state.first===0?'正':'反',duration:1800});void event(r,{type:'coinResult',owner:r.engine.state.first,coin:r.engine.state.first===0?'正':'反',duration:1900});void event(r,{type:'networkOpening',duration:1000});publish(r);}result={ok:true};break;
 case '/api/setup':case '/api/setupUndo':if(r.phase!=='setup'||p.setupReady)fail('不能调整布置。',409);{const id=r.engine.state.players[seat].hand[d.index];if(!r.engine.networkSetup(seat,d.index,d.slot??null,url.pathname.endsWith('Undo')?d.uid:null))fail('这个位置不能放置该精灵。');if(url.pathname==='/api/setup'){const target=d.slot==null?r.engine.state.players[seat].active:r.engine.state.players[seat].bench.find(m=>m.slot===d.slot);void event(r,{type:'networkSetupPlace',owner:seat,cardId:id,target:target.uid,index:d.index,slot:d.slot??null,duration:1750});}}publish(r);result={ok:true};break;
 case '/api/setupDone':if(r.phase!=='setup'||!r.engine.state.players[seat].active)fail('请先放置战斗精灵。');p.setupReady=true;publish(r);if(r.players.every(x=>x.setupReady)){r.phase='play';void run(r,()=>r.engine.networkBeginBattle());}result={ok:true};break;
 case '/api/action':if(r.phase!=='play'||r.engine.state.current!==seat||r.pending||r.running)fail('现在不能执行操作。',409);if(d.seq!==r.seq)fail('场面已更新，请重新操作。',409);if(!d.action||typeof d.action!=='object')fail('操作格式错误。');{const a=clone(d.action),cmp={...a};delete cmp.slot;delete cmp.targetUid;if(a.slot!==undefined&&(!Number.isInteger(a.slot)||a.slot<0||a.slot>2||r.engine.state.players[seat].bench.some(m=>m.slot===a.slot)))fail('备战位置不可用。');if(a.targetUid!==undefined&&a.targetUid!==null&&!Number.isInteger(a.targetUid))fail('目标格式错误。');if(!r.engine.legalActions(seat).some(x=>JSON.stringify(x)===JSON.stringify(cmp)))fail('操作不符合当前规则。');void run(r,async()=>{if(!await r.engine.perform(seat,a))throw new Error('操作失效');});}result={ok:true};break;
 case '/api/choice':{const c=r.pending;if(!c||c.owner!==seat||c.id!==d.choiceId)fail('选择已失效。',409);if(c.allocation){const spec=c.allocation,valid=d.value===null&&c.optional||Array.isArray(d.value)&&d.value.length===spec.tokens.length&&d.value.every(uid=>uid===null&&c.optional||c.options.some(o=>o.value===uid))&&(!spec.singleTarget||new Set(d.value.filter(uid=>uid!==null)).size<=1);if(!valid)fail('能量分配不符合规则。');}else if(!(d.value===null&&c.optional)&&!c.options.some(o=>JSON.stringify(o.value)===JSON.stringify(d.value)))fail('请选择有效选项。');r.pending=null;const value=d.value;c.resolve(value);result={ok:true};break;}
 case '/api/surrender':if(!['setup','play'].includes(r.phase))fail('当前没有进行中的对局。');finish(r,'玩家'+(2-seat)+'获胜','玩家'+(seat+1)+'认输。');result={ok:true};break;
 case '/api/rematch':if(r.phase!=='finished')fail('请先结束本局。');p.again=true;publish(r);if(r.players.every(x=>x.again)){r.phase='lobby';r.round++;r.players.forEach(x=>{x.ready=false;x.setupReady=false;x.again=false;});r.engine=engineFor(r);publish(r);}result={ok:true};break;
 case '/api/leave':if(['setup','play'].includes(r.phase))finish(r,'玩家'+(2-seat)+'获胜','玩家离开房间。');sessions.delete(p.token);clearTimeout(p.disconnectTimer);p.stream?.end();p.stream=null;if(r.phase==='lobby'){r.players[seat]=null;if(seat===0&&r.players[1]){sessions.delete(r.players[1].token);r.players[1].stream?.end();rooms.delete(r.code);}else if(!r.players.some(Boolean))rooms.delete(r.code);else publish(r);}result={ok:true};break;
 default:fail('接口不存在。',404);}
 }if(!res.headersSent){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(result));}}
const extraOrigins=new Set((process.env.APP_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean));
function cors(req,res){const origin=req.headers.origin;if(!origin)return;const same=origin===`http://${req.headers.host}`||origin===`https://${req.headers.host}`;if(origin!=='null'&&!same&&!extraOrigins.has(origin))fail('请求来源不正确。',403);res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Max-Age','600');}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname.startsWith('/api/')){cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}if(url.pathname==='/api/health'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});return res.end(JSON.stringify({ok:true,cardsVersion:"A0-A1-20261006-r8"}));}}if(url.pathname.startsWith('/api/'))return await api(req,res,url);let filename=url.pathname==='/'?'/index-battle.html':decodeURIComponent(url.pathname);const full=path.resolve(ROOT,'.'+filename);const allowed=full.startsWith(assetRoot+path.sep)||['index-battle.html','pvp-client.js','pvp-config.js','battle-addon.js'].some(n=>full===path.join(ROOT,n));if(!allowed||!fs.existsSync(full)||!fs.statSync(full).isFile())fail('文件不存在。',404);res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.avif':'image/avif','.webp':'image/webp'})[path.extname(full).toLowerCase()]||'application/octet-stream','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});fs.createReadStream(full).pipe(res);}catch(e){if(!res.headersSent)res.writeHead(e.status||500,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify({error:e.status?e.message:'服务暂时不可用。'}));}});
setInterval(()=>{for(const [c,r]of rooms)if(!r.players.some(p=>p?.stream)&&Date.now()-r.updated>30*60000){r.players.forEach(p=>{if(p)sessions.delete(p.token)});rooms.delete(c);}for(const [ip,b]of rate)if(Date.now()-b.start>120000)rate.delete(ip);},60000).unref();
server.listen(PORT,'0.0.0.0',()=>console.log(`洛克好友约战：http://localhost:${PORT} （同局域网可用本机IP访问）`));

